CREATE COLUMN TABLE "SalesOrders" ("SALESORDERID" NVARCHAR(10) NOT NULL , "CREATEDBY" NVARCHAR(10), "CREATEDAT" DATE, "CHANGEDBY" NVARCHAR(10), "CHANGEDAT" DATE , "FISCVARIANT" NVARCHAR(2), "FISCALYEARPERIOD" NVARCHAR(7), "NOTEID" NVARCHAR(10), "PARTNERID" NVARCHAR(10), "SALESORG" NVARCHAR(4), "CURRENCY" NVARCHAR(5), "GROSSAMOUNT" DECIMAL(15,2) , "NETAMOUNT" DECIMAL(15,2) , "TAXAMOUNT" DECIMAL(15,2) , "LIFECYCLESTATUS" NVARCHAR(1), "BILLINGSTATUS" NVARCHAR(1), "DELIVERYSTATUS" NVARCHAR(1), PRIMARY KEY ("SALESORDERID")) UNLOAD PRIORITY 5  AUTO MERGE ;
COMMENT ON TABLE "SalesOrders" is 'Sales orders';
COMMENT ON COLUMN "SalesOrders"."SALESORDERID" is 'Sales order ID';
COMMENT ON COLUMN "SalesOrders"."CREATEDBY" is 'Created by';
COMMENT ON COLUMN "SalesOrders"."CREATEDAT" is 'Created at date';
COMMENT ON COLUMN "SalesOrders"."CHANGEDBY" is 'Changed by';
COMMENT ON COLUMN "SalesOrders"."CHANGEDAT" is 'Changed at date';
COMMENT ON COLUMN "SalesOrders"."FISCVARIANT" is 'Fiscal year variant';
COMMENT ON COLUMN "SalesOrders"."FISCALYEARPERIOD" is 'Fiscal year period';
COMMENT ON COLUMN "SalesOrders"."NOTEID" is 'Note ID';
COMMENT ON COLUMN "SalesOrders"."PARTNERID" is 'Partner ID';
COMMENT ON COLUMN "SalesOrders"."SALESORG" is 'Sales Organisation';
COMMENT ON COLUMN "SalesOrders"."CURRENCY" is 'Currency key';
COMMENT ON COLUMN "SalesOrders"."GROSSAMOUNT" is 'Gross amount';
COMMENT ON COLUMN "SalesOrders"."NETAMOUNT" is 'Net amount';
COMMENT ON COLUMN "SalesOrders"."TAXAMOUNT" is 'Tax amount';
COMMENT ON COLUMN "SalesOrders"."LIFECYCLESTATUS" is 'Life cycle status';
COMMENT ON COLUMN "SalesOrders"."BILLINGSTATUS" is 'Billing status';
COMMENT ON COLUMN "SalesOrders"."DELIVERYSTATUS" is 'Delivery status'