CASE 
  WHEN 
       UPPER(REVIEW_TITLE) LIKE '%GOOD%' 
    OR UPPER(REVIEW_TITLE) LIKE '%GREAT%' 
    OR UPPER(REVIEW_TITLE) LIKE '%EXCELLENT%' 
    OR UPPER(REVIEW_TITLE) LIKE '%HAPPY%' 
    OR UPPER(REVIEW_TITLE) LIKE '%SUPER%' 
  THEN 1 
  WHEN
       UPPER(REVIEW_TITLE) LIKE '%BAD%' 
    OR UPPER(REVIEW_TITLE) LIKE '%FAKE%' 
    OR UPPER(REVIEW_TITLE) LIKE '%WASTE%' 
    OR UPPER(REVIEW_TITLE) LIKE '%EXPENSIVE%' 
    OR UPPER(REVIEW_TITLE) LIKE '%BROKE%' 
    OR UPPER(REVIEW_TITLE) LIKE '%NOT%' 
  THEN -1  
  ELSE 0 
END